stages:
  - build
  - test
  - deploy

amsbuild:
  stage: build
  script:
    - export GOPATH=$HOME/go
    - docker build -f build/docker/ams/Dockerfile -t ams .

agencybuild:
  stage: build
  script:
    - export GOPATH=$HOME/go
    - docker build -f build/docker/agency/Dockerfile -t agency .

loggerbuild:
  stage: build
  script:
    - export GOPATH=$HOME/go
    - docker build -f build/docker/logger/Dockerfile -t logger .

dfbuild:
  stage: build
  script:
    - export GOPATH=$HOME/go
    - docker build -f build/docker/df/Dockerfile -t df .
    
stubbuild:
  stage: build
  script:
    - export GOPATH=$HOME/go
    - cd cmd/kubestub
    - CGO_ENABLED=0 GOOS=linux go build main.go

# amstest:
#   stage: test
#   only:
#     - master
#   script:
#     - cd pkg/ams
#     - CGO_ENABLED=0 go test -coverpkg=./...

agencytest:
  stage: test
  script:
    - cd pkg/agency
    - CGO_ENABLED=0 go test -coverpkg=./...

loggertest:
  stage: test
  script:
    - cd pkg/logger
    - CGO_ENABLED=0 go test -coverpkg=./...

amsdeploy:
  stage: deploy
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.git.rwth-aachen.de
    - docker tag ams registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/ams
    - docker push registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/ams

agencydeploy:
  stage: deploy
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.git-ce.rwth-aachen.de
    - docker tag agency registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/agency
    - docker push registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/agency

loggerdeploy:
  stage: deploy
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.git-ce.rwth-aachen.de
    - docker tag logger registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/logger
    - docker push registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/logger

dfdeploy:
  stage: deploy
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.git-ce.rwth-aachen.de
    - docker tag df registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/df
    - docker push registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/df
