stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: golang:1.13.8
  script:
    - cd cmd/ams
    - CGO_ENABLED=0 GOOS=linux go build -ldflags '-s' -o ams
    - cd ../agency
    - CGO_ENABLED=0 GOOS=linux go build -ldflags '-s' -o agency
    - cd ../benchmark
    - CGO_ENABLED=0 GOOS=linux go build -ldflags '-s' -o benchmark
    - cd ../logger
    - CGO_ENABLED=0 GOOS=linux go build -ldflags '-s' -o logger
    - cd ../df
    - CGO_ENABLED=0 GOOS=linux go build -ldflags '-s' -o df
    - cd ../plugnplay
    - CGO_ENABLED=0 GOOS=linux go build -ldflags '-s' -o pnp
    - cd ../frontend
    - CGO_ENABLED=0 GOOS=linux go build -ldflags '-s' -o frontend
    - cd ../kubestub
    - CGO_ENABLED=0 GOOS=linux go build -ldflags '-s' -o kubestub

test:
  stage: test
  image: golang:1.13.8
  script:
    - cd pkg
    - go test ./... -coverprofile cover.out
    - go tool cover -func cover.out

deploy:
  stage: deploy
  image: docker:19.03.12
  only:
    - master
    - develop
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.git.rwth-aachen.de
    - docker build -f build/docker/ams/Dockerfile -t ams .
    - docker tag ams registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/ams
    - docker push registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/ams
    - docker build -f build/docker/agency/Dockerfile -t agency .
    - docker tag agency registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/agency
    - docker push registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/agency
    - docker build -f build/docker/benchmark/Dockerfile -t benchmark .
    - docker tag benchmark registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/benchmark
    - docker push registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/benchmark
    - docker build -f build/docker/logger/Dockerfile -t logger .
    - docker tag logger registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/logger
    - docker push registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/logger
    - docker build -f build/docker/df/Dockerfile -t df .
    - docker tag df registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/df
    - docker push registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/df
    - docker build -f build/docker/plugnplay/Dockerfile -t plugnplay .
    - docker tag plugnplay registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/plugnplay
    - docker push registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/plugnplay
    - docker build -f build/docker/frontend/Dockerfile -t frontend .
    - docker tag frontend registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/frontend
    - docker push registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/frontend
    - docker build -f build/docker/clonemap_local/Dockerfile -t clonemap_local .
    - docker tag clonemap_local registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/clonemap_local
    - docker push registry.git.rwth-aachen.de/acs/public/cloud/mas/clonemap/clonemap_local
